apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-vkcj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-vkcj
    app.kubernetes.io/part-of: tkrw-pr712-0075-0029-app
  name: devfile-sample-vkcj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-vkcj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-vkcj
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0029-tenant/tkrw-pr712-0075-0029-app/devfile-sample-vkcj@sha256:504ea06a5ba9fc672346bdc50c3d4388fef6981c86cfdfc79b1527159a087b76
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
