apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-vkcj
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0029-tenant/tkrw-pr712-0075-0029-app/devfile-sample-vkcj@sha256:504ea06a5ba9fc672346bdc50c3d4388fef6981c86cfdfc79b1527159a087b76
        name: my-nodejs
        resources: {}
status: {}
